spring:
  datasource:
    hikari:
      master:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://131.186.27.99:5432/postgres
        username: postgres
        password: new1234!
      slave:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://131.186.27.99:5432/cm_park
        username: pcm01
        password: mook
##    
#    oracle:
##        driver-class-name: ENC(JDb9mZorNx1OO9YHTZU5Dg8u54qQn0Bf1rakK733oOozcxEbtA7mtQ==)
##        jdbc-url: ENC(go/cM6ItkbcXncj2obU+wc+rmTH2x6Hc0Ik7IrLjYlsWIGW6ThrSBOKYgl/MnE0I)
##        username: ENC(9xBLxHfVfjCpcMOgx2g+qQ==)
##        password: ENC(XKp0btpEVWbkvEt+QkZBPUc5osos2j4L)
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#        jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCL
#        username: system
#        password: Mook@2736
#    jndi-name: jndi/postgresDS
  
  jpa:
    showSql: true
    properties:
      hibernate.format_sql: true
  
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
        
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
  
#logging:
#  level:
#    '[org.springframework.web.client]': debug
#    '[org.hibernate.sql]': debug
#    '[org.hibernate.type.descriptor.sql]': trace